### ISSUE TITLE
Warning about typo

### ISSUE THREAD

**Issue by pkrefta** [leereilly/csi#4]
Hey,

I'm using CSI 0.3.1 and everytime I do something in console I see a warning
`/Users/pkrefta/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/csi-0.3.1/lib/csi/record.rb:16: warning: found = in conditional, should be ==`
I've seen a commit fixing this but has it been released ?

**Comment by maniempire** [comment]
Hi,
I am also seeing the warning every time i start the server. Let me know when this fix will be available in the release.

**Comment by allenwlee** [comment]
+1 same here

**Comment by leereilly** [comment]
Thanks, guys. I just released a new version via https://rubygems.org/gems/csi :sunglasses: 

![](http://media2.giphy.com/media/PcTzEWBzqiL5u/giphy.gif)

**Comment by maniempire** [comment]
Hi,

```
Thanks for this release. Let me check and confirm with the latest version.
```

Thanks,
Mani
